name: CI
on:
  pull_request:
  merge_group:
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Log some stuff
        run: printenv && git show
        
      - name: Hang for a minute
        run: sleep 15

      - name: Exit
        run: |
          exit $(cat exit)

